spring:
  flyway:
    enabled: true
    ignore-missing-migrations: true
    locations: classpath:/migration
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/jd2_airsales"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: 297113973
    url: "jdbc:postgresql://localhost:5432/jd2_airsales"
    driver-class-name: org.postgresql.Driver

  main:
    allow-bean-definition-overriding: true
    #  autoconfigure:
    #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

hibernate:
  cache:
    provider_class: net.sf.ehcache.hibernate.SingletonEhCacheProvider
    use_second_level_cache: true

server:
  port: 8080

jwtconfig:
  secret: "ZvkYYnyM929FM4NW9_hSis7_x3_9rymsDAx9yuOcc1I"
  expiration: 1500000

roleconfiguration:
  hierarchy: "ROLE_SUPERADMIN > ROLE_ADMIN \n ROLE_AMIN > ROLE_MANAGER \n ROLE_MANAGER > ROLE_USER"

