create table airport
(
	airport_id smallint generated by default as identity (maxvalue 32767)
		constraint airports_pkey
			primary key,
	airport_name varchar(200) not null
		constraint airports_idx_airports_name01
			unique,
	airport_short_name varchar(4) not null
		constraint airport_airport_short_name_key
			unique,
	airpot_location varchar(100),
	disabled boolean default false not null
);

alter table airport owner to postgres;

create table roles
(
	roles_id smallint generated by default as identity (maxvalue 32767)
		constraint roles_pkey
			primary key,
	role_name varchar(20) not null
		constraint roles_idx_role_name02
			unique,
	permissions varchar(40) not null,
	disabled boolean default false not null
);

alter table roles owner to postgres;

create index roles_idx_role_name01
	on roles (role_name);

create table users
(
	user_id integer generated by default as identity
		constraint users_pkey
			primary key,
	user_role smallint default 1 not null
		constraint "FK_user_roles"
			references roles,
	login varchar(40) not null
		constraint user_idx_login02
			unique,
	password varchar(140) not null,
	disabled boolean default false not null
);

alter table users owner to postgres;

create table airline
(
	airline_id smallint generated by default as identity (maxvalue 32767)
		constraint "Airline_pkey"
			primary key,
	airline_name varchar(100) not null
		constraint airline_airline_name_key
			unique,
	airline_short_name varchar(3) not null
		constraint airline_idx_airline_short_name01
			unique,
	disabled boolean default false not null
);

alter table airline owner to postgres;

create index "Airline_idx_airline_short_name01"
	on airline (airline_short_name);

create table plane
(
	plane_id integer generated by default as identity
		constraint "Plane_pkey"
			primary key,
	aircraft_number varchar(9) not null
		constraint plane_aircraft_number_key
			unique,
	properties varchar(100),
	disabled boolean default false not null
);

alter table plane owner to postgres;

create table seat_class
(
	seat_class_id smallint generated by default as identity (maxvalue 32767)
		constraint seat_class_pkey
			primary key,
	seat_class_name varchar(30) not null
		constraint seat_class_idx_seat_class_name01
			unique,
	disabled boolean default false not null
);

alter table seat_class owner to postgres;

create table plane_seats
(
	plane_seats_id integer generated by default as identity
		constraint plane_seats_pkey
			primary key,
	plane integer not null
		constraint "FK_planeseats_plane"
			references plane,
	seat_class smallint not null
		constraint "FK_planeseats_seatclass"
			references seat_class,
	number_of_seats smallint not null,
	disabled boolean default false not null
);

alter table plane_seats owner to postgres;

create index plane_seats_idx_plane01
	on plane_seats (plane);

create table airline_plane
(
	plane integer not null
		constraint "FK_airlineplane_plane"
			references plane,
	airline smallint not null
		constraint "FK_airlineplane_airline"
			references airline,
	airline_plane_id bigserial not null
		constraint airline_plane_pk
			primary key,
	disabled boolean default false not null
);

alter table airline_plane owner to postgres;

create index airline_plane_plane_airline_index
	on airline_plane (plane, airline);

create table flight
(
	flight_id integer generated by default as identity
		constraint flight_pkey
			primary key,
	flight_number varchar(7) not null,
	airline smallint not null
		constraint "FK_flight_airline"
			references airline,
	airport_departure smallint not null
		constraint "FK_flightdeparture_airport"
			references airport,
	airport_destination smallint not null
		constraint "FK_flightDestination_airport"
			references airport,
	disabled boolean default false not null
);

alter table flight owner to postgres;

create index flight_idx_flight_number01
	on flight (flight_number);

create table flight_plane
(
	flight integer not null
		constraint "FK_flightplane_flight"
			references flight,
	plane integer not null
		constraint "FK_flifhtplane_plane"
			references plane,
	flight_plane_id bigserial not null
		constraint flight_plane_pk
			primary key,
	disabled boolean default false not null
);

alter table flight_plane owner to postgres;

create index flight_plane_flight_plane_index
	on flight_plane (flight, plane);

create table discount
(
	discount_id smallint generated by default as identity (maxvalue 32767)
		constraint discount_pkey
			primary key,
	discount_name varchar(30) not null
		constraint discount_idx_discount_name01
			unique,
	discount_value smallint not null,
	disabled boolean default false not null
);

alter table discount owner to postgres;

create table passenger_class
(
	passenger_class_id smallint generated by default as identity (maxvalue 32767)
		constraint passenger_class_pkey
			primary key,
	passenger_class_name varchar(30) not null
		constraint passenger_class_passenger_class_name_key
			unique,
	passenger_class_properties varchar(40) not null,
	disabled boolean default false not null
);

alter table passenger_class owner to postgres;

create table passenger
(
	passenger_id bigint generated by default as identity
		constraint passenger_pkey
			primary key,
	first_name varchar(100) not null,
	last_name varchar(100) not null,
	passenger_class smallint not null
		constraint "FK_passenger_passengerclass"
			references passenger_class,
	comments varchar(100),
	disabled boolean default false not null
);

alter table passenger owner to postgres;

create index passenger_idx_last_name01
	on passenger (last_name);

create table country
(
	country_id smallint generated by default as identity (maxvalue 32767)
		constraint country_pkey
			primary key,
	country_name varchar(150) not null
		constraint country_idx_country_name01
			unique,
	disabled boolean default false not null
);

alter table country owner to postgres;

create table passport
(
	passport_id bigserial not null
		constraint passport_pkey
			primary key,
	first_name_latin varchar(100) not null,
	last_name_latin varchar(100) not null,
	series varchar(12) not null,
	expire_date date not null,
	citizenship smallint not null
		constraint "FK_passport_country"
			references country,
	disabled boolean default false not null
);

alter table passport owner to postgres;

create table ticket_status
(
	ticket_status_id smallserial not null
		constraint ticket_status_pk
			primary key,
	ticket_status_name varchar(20) not null,
	disabled boolean default false not null
);

alter table ticket_status owner to postgres;

create unique index ticket_status_ticket_status_name_uindex
	on ticket_status (ticket_status_name);

create unique index ticket_status_ticket_status_id_uindex
	on ticket_status (ticket_status_id);

create table current_flight_status
(
	current_flight_status_id smallserial not null
		constraint current_flight_status_pk
			primary key,
	current_flight_status_name varchar(20),
	disabled boolean default false not null
);

alter table current_flight_status owner to postgres;

create unique index current_flight_status_current_flight_status_id_uindex
	on current_flight_status (current_flight_status_id);

create table current_flight
(
	current_flight_id bigint generated by default as identity (maxvalue 2147483647)
		constraint current_flight_pkey
			primary key
		constraint current_flight__current_flight_status_fk
			references current_flight_status,
	flight_plane bigint not null
		constraint current_flight_flight_plane_flight_plane_id_fk
			references flight_plane,
	departure_date timestamp not null,
	arrival_date timestamp not null,
	baseprice numeric not null,
	current_flight_status smallint not null,
	flight integer not null
		constraint current_flight_flight_flight_id_fk
			references flight,
	disabled boolean default false not null
);

alter table current_flight owner to postgres;

create table ticket
(
	ticket_id bigint generated by default as identity (maxvalue 2147483647)
		constraint ticket_pkey
			primary key
		constraint ticket_ticket_status_ticket_status_id_fk
			references ticket_status,
	passport bigint not null
		constraint ticket_passport_passport_id_fk
			references passport,
	current_flight bigint
		constraint "FK_ticket_currentflight"
			references current_flight,
	discount smallint not null
		constraint "FK_ticket_diskount"
			references discount,
	final_price numeric not null,
	ticket_status smallint not null,
	seat integer not null
		constraint ticket_plane_seats_plane_seats_id_fk
			references plane_seats,
	disabled boolean default false not null
);

alter table ticket owner to postgres;

create table user_passenger
(
	user_passenger bigserial not null
		constraint user_passenger_pk
			primary key,
	user_id integer not null
		constraint user_passenger_user_user_id_fk
			references users,
	passenger bigint not null
		constraint user_passenger_passenger_passenger_id_fk
			references passenger,
	disabled boolean default false not null
);

alter table user_passenger owner to postgres;

create index user_passenger_user_passenger_index_2
	on user_passenger (user_id, passenger);

create table passenger_passport
(
	passenger_passport_id bigserial not null
		constraint passenger_passport_pk
			primary key,
	passenger bigint not null
		constraint passenger_passport_passenger_passenger_id_fk
			references passenger,
	passport bigint not null
		constraint passenger_passport_passport_passport_id_fk
			references passport,
	disabled boolean default false not null
);

alter table passenger_passport owner to postgres;

create index passenger_passport_passenger_passport_index
	on passenger_passport (passenger, passport);

